### ISSUE TITLE
CSRF Example failing 

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#810]
### Question

Attempting to use the example at the bottom of https://badgerati.github.io/Pode/Tutorials/Middleware/Types/CSRF/

The view generates the webpage, but when pressing submit Pode says the CSRF token is invalid.

**Comment by Badgerati** [comment]
The `Enable-PodeSessionMiddleware` is missing a `-Duration` :) I did fix all of these at one point, must have slipped through the cracks!

Set the session to the following, and it should be good:
```powershell
Enable-PodeSessionMiddleware -Duration 120
```

**Comment by phatmandrake** [comment]
Okay it refreshes now without error, but I'm not seeing the flash message 🤔

**Comment by Badgerati** [comment]
Huh, I just ran the example (with the above change) and get the flash message back 🤔 

![image](https://user-images.githubusercontent.com/1483395/130332857-98149deb-071d-45a2-a199-ce8c728b45b5.png)

**Comment by phatmandrake** [comment]
```powershell
Start-PodeServer -Browse {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http
    Set-PodeViewEngine -Type Pode

    # setup session and csrf middleware
    Enable-PodeSessionMiddleware -Secret 'vegeta' -Duration 120
    Enable-PodeCsrfMiddleware

    # this route will work, as GET methods are ignored by CSRF by default
    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        $token = (New-PodeCsrfToken)
        Write-PodeViewResponse -Path 'index' -Data @{ 'csrfToken' = $token } -FlashMessages
    }

    # POST route for form which will require the csrf token from above
    Add-PodeRoute -Method Post -Path '/token' -ScriptBlock {
        Add-PodeFlashMessage -Name 'message' -Message $WebEvent.Data['message']
        Move-PodeResponseUrl -Url '/'
    }
}
```

**Comment by Badgerati** [comment]
Yup, works fine 👀 

![image](https://user-images.githubusercontent.com/1483395/130333316-a62cd5f8-c1f8-4055-bf10-f70a577b5a44.png)

**Comment by phatmandrake** [comment]
Interesting. Test-PodeFlashMessage doesn't seem to recognize the the message exist if I test for it at the default path before the view response. It does after it adds the flash message in the Token route.

Does this imply it may not be tracking the session?

**Comment by Badgerati** [comment]
I did this:
```powershell
Start-PodeServer -Browse {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http
    Set-PodeViewEngine -Type Pode

    # setup session and csrf middleware
    Enable-PodeSessionMiddleware -Secret 'vegeta' -Duration 120
    Enable-PodeCsrfMiddleware

    # this route will work, as GET methods are ignored by CSRF by default
    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        $token = (New-PodeCsrfToken)
        Test-PodeFlashMessage -Name 'message' | Out-Default
        Write-PodeViewResponse -Path 'index' -Data @{ 'csrfToken' = $token } -FlashMessages
    }

    # POST route for form which will require the csrf token from above
    Add-PodeRoute -Method Post -Path '/token' -ScriptBlock {
        Add-PodeFlashMessage -Name 'message' -Message $WebEvent.Data['message']
        Test-PodeFlashMessage -Name 'message' | Out-Default
        Move-PodeResponseUrl -Url '/'
    }
}
```

I get `False` on the initial page load, but thereafter I get `True` from the `/token` route and the `/` route 🤔 

Is the code above similar to what you have with your `Test-PodeFlashMessage` or different?

**Comment by phatmandrake** [comment]
I'm getting False-True -False. It doesn't think there's a flash message after the redirect.

**Comment by Badgerati** [comment]
That is strange 🤔  which version of Pode/PowerShell are you using? Because you're right, that does sound like something's preventing it from saving the session's data.

All this is running locally your your machine, I assume?

**Comment by phatmandrake** [comment]
Local, MacOS, 7.1.4, 2.4.1
All up to date.

**Comment by Badgerati** [comment]
I just tried those on Windows and Ubuntu, both worked as expected 🤔 Are you able to try either of those and see what happens?

Do you get anything by adding `New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging` as well? Just in case.

**Comment by phatmandrake** [comment]
Man I am really striking out today.

CentOS 8: (Currently using for REST endpoints). Started another instance of pode, for some reason Pode is unable to find index.pode and returns 404 --- the file is for sure in the current directory that pode is being invoked from. No idea what that's about ....

Windows: Still No flash message. First time install for Pode there as well.

**Comment by phatmandrake** [comment]
When I ran the server as root these errors popped up 

![image](https://user-images.githubusercontent.com/24230425/130336274-547cec8e-f7f8-49fd-a7db-cab035601ee1.png)

**Comment by Badgerati** [comment]
This is bizarre! I just tried on a fresh Windows VM and it worked 🤯 

The errors from CentOS are probably because there's no browser to be opened - removing `-Browser` should stop those.

I guess to be absolutely sure I'm doing everything the same: if you're using the just the example would just be able to attach a zip/7z of the server? If not, could you show a screenshot of the file/folder structure; an example of the code (which I'm guessing is just the example! 😂); and the steps you're taking on the page/form itself?

**Comment by phatmandrake** [comment]
[Flash_Message_Test.zip](https://github.com/Badgerati/Pode/files/7027947/Flash_Message_Test.zip)

**Comment by Badgerati** [comment]
First thing I spotted is the index.pode should be in a views folder :) I've updated the docs to fix that it doesn't mention that!

![image](https://user-images.githubusercontent.com/1483395/130675619-6b6117a5-b5b0-4b00-8ca0-27ac2611cc60.png)

After that, it works for me (on Windows it worked even without the views folder, which I probably need to look into!) 🤔

**Comment by phatmandrake** [comment]
I'm gonna find another laptop to try this on 
https://user-images.githubusercontent.com/24230425/130709543-5a214786-8434-4909-8765-6e8397b5edf5.mov

**Comment by phatmandrake** [comment]
I have tried on 4 computers with the same results a Windows 10 VM, A Centos 8 VM, A Win Server 2016 VM, MacOS Catalina.

All of them have the same issue. Dx

**Comment by phatmandrake** [comment]
And I finally got ahold of another Mac - fresh build - Pode 1.4.1 - PS 7.1.4 - still not working.

Maybe you can give me a zip file of you working one.

**Comment by Badgerati** [comment]
Hey, apologies for the late response here 🙇  - I was finishing up the release over on Pode.Web, but can get back to doing work on Pode now.

Sessions and Headers requires Authentication, ([here](https://badgerati.github.io/Pode/Tutorials/Routes/Examples/RestApiSessions/)), the idea for them is so a user can use a REST call to login, supply the session for other requests, then logout. If you've got a scenario for sessions on a REST API with no authentication, I can look into it!

This is where I'm wondering if something strange is happening to the cookie. When a user logs in via the frontend Pode creates and storage a SessionId with data in-mem, and this SessionId is sent back to the browser as a `Set-Cookie` header to create the cookie. On subsequent requests from the browser, the browser automatically resends current, non-expired, cookies on all requests. Pode parses these cookies from the request, one hopefully being pode.sid, and uses the value of that to retrieve the Session data.

Now I've released Pode.Web I'll look into this more, one idea I had is what happens if you set the `-Duration` to something crazy? Like `-Duration 604800` so it expires after a week?

---

`Get-PodeSessionId` only returns the SessionId if the current session is for an authenticated user, but in hindsight it should probably just just return the current SessionId regardless.

If the request doesn't contain a a pode.sid cookie or header, or the SessionId is invalid, then Pode will regenerate a new one each time. The session is only saved and returned as a cookie/header on response if data is set on the session (like `Views++` or the authenticated user)

**Comment by phatmandrake** [comment]
`If you've got a scenario for sessions on a REST API with no authentication, I can look into it.`

Well there's an easy way around it so probably not worth the effort to do anything specific about it now at least. 😄 

`if you set the -Duration to something crazy? Like -Duration 604800 so it expires after a week?`
Setting `-Duration 18001` is the minimum number that works.  

If the request doesn't contain a a pode.sid cookie or header, or the SessionId is invalid, then Pode will regenerate a new one each time. So is the default behavior that using session middleware generates a cookie unless you specify header?

**Comment by Badgerati** [comment]
I think I've got it!

If you're able to update the Pode module locally, what happens if you change the following line:

https://github.com/Badgerati/Pode/blob/0f5a522cc71499f86d27ce8165ece295ba31f3fa/src/Private/Sessions.ps1#L202

to be:

```powershell
$expiry = $Session.Properties.TimeStamp.ToUniversalTime()
```

instead? :D

I span up a server in Central US when we were first looking at this and CSRF was fine. But your 18001s is bang on UTC -05:00, so figured I'd try again. BOOM, this time it stopped working for me too!

Turns out, the expiry is read from the cookie, but is converted to local time, not UTC. So when it check UTC Now vs Local Now it's expired. Changing that one line to convert to UTC fixed it on my VM 😄 

---

And yes, session middleware will use cookies by default, unless `-UseHeader` is specified when enabling sessions.

**Comment by phatmandrake** [comment]
Badgerati for the win! 

Ah UTC the DNS of time 🤣 . This should go down in Pode bug history.

**Comment by Badgerati** [comment]
> This should go down in Pode bug history

Hahah, yes definitely! 😂 

I've pushed a more full commit to fix this (and the missing Add-PodeEndpoint in the docs!). I'll look at getting this out into a v2.4.2 will some other bugs - rather than waiting for v2.5.0! 😃
